name: Dotfiles CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ShellCheck
        run: shellcheck install.sh verify.sh update.sh bootstrap.sh scripts/linux/*.sh

  lint-powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path .\install.ps1 -Recurse -EnableExit -Severity Error
          Invoke-ScriptAnalyzer -Path .\bootstrap.ps1 -Recurse -EnableExit -Severity Error
          Invoke-ScriptAnalyzer -Path .\windows\Microsoft.PowerShell_profile.ps1 -Recurse -EnableExit -Severity Error
          Invoke-ScriptAnalyzer -Path .\verify.ps1 -Recurse -EnableExit -Severity Error

  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate JSON files
        run: |
          jq empty themes/catppuccin_mocha.omp.json
          jq empty windows/settings.json
